server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        if ($request_filename ~* \.(html|htm)$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate, private";
        }
    }

    location /trt-proxy/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD';
            add_header 'Access-Control-Allow-Headers' '*';
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        proxy_pass https://trt.daioncdn.net/;
        proxy_ssl_server_name on;
        proxy_set_header Host trt.daioncdn.net;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, HEAD";
        add_header Access-Control-Allow-Headers "*";

        add_header Cache-Control "no-cache, no-store, must-revalidate, private" always;
        add_header Pragma "no-cache" always;
        add_header Expires 0 always;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
