name: Auto Deploy to Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook (Domain HTTPS)
        run: |
          echo "Triggering deploy via domain HTTPS..."
          curl -i -X POST "https://dokploy.workyghost.com/api/deploy/bvMvWy-zMeobe-_JpCwAE"
      - name: Trigger Webhook (IP Port 3000)
        run: |
          echo "Triggering deploy via IP and Port 3000..."
          curl -i --max-time 10 -X POST "http://13.140.143.25:3000/api/deploy/bvMvWy-zMeobe-_JpCwAE" || true
